
import { EssayResult } from "../types";

/**
 * Extracts raw text from a .docx file using mammoth.js
 */
const extractTextFromDocx = async (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = async (event) => {
      const arrayBuffer = event.target?.result as ArrayBuffer;
      try {
        // @ts-ignore - mammoth is loaded globally via CDN
        const result = await window.mammoth.extractRawText({ arrayBuffer });
        resolve(result.value);
      } catch (err) {
        reject(err);
      }
    };
    reader.onerror = reject;
    reader.readAsArrayBuffer(blob);
  });
};

const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = (reader.result as string).split(',')[1];
      resolve(base64String);
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

export const scoreEssay = async (
  fileName: string, 
  content: string | Blob, 
  mimeType: string
): Promise<Partial<EssayResult>> => {
  const isMultimodal = mimeType.startsWith('image/');
  const endpoint = isMultimodal 
    ? 'https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation'
    : 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation';

  const systemPrompt = `
    You are a DETERMINISTIC SCORING ENGINE. Absolute consistency is required.
    
    EVALUATION PROTOCOL (Total 100 Points):
    1. LOGIC & FLOW (60 Points Total) - THE CRITICAL COMPONENT:
       - Pillar A: STRUCTURAL INTEGRITY (15 pts) - Intro, Body, Conclusion present.
       - Pillar B: ARGUMENTATIVE SEQUENCE (15 pts) - Point -> Evidence -> Explanation flow.
       - Pillar C: CONNECTIVITY (15 pts) - Use of 4+ unique logical transitions.
       - Pillar D: THESIS CONSISTENCY (15 pts) - Conclusion reinforces the intro thesis.

    2. CONTEXT & VALUES (20 Points Total):
       Award 2.22 pts for each of these 9 values found: Leadership, Versatility, Safety, Vision, Innovation, Customer-orientation, Positive Communication, Teamwork, Result-driven performance.

    3. GRAMMAR & VOCABULARY (20 Points Total):
       Start at 20. Subtract 2 pts for every unique major error.

    OUTPUT FORMAT (Strict JSON):
    {
      "score": number,
      "reason": "max 30 words explaining logic score and found values",
      "summary": "max 100 words overview",
      "isSuspectedAI": boolean
    }
  `;

  try {
    let payload: any;

    if (isMultimodal) {
      const base64Data = await blobToBase64(content as Blob);
      payload = {
        model: "qwen-vl-max",
        input: {
          messages: [
            {
              role: "user",
              content: [
                { text: systemPrompt },
                { image: `data:${mimeType};base64,${base64Data}` },
                { text: "Analyze this essay image according to the protocol." }
              ]
            }
          ]
        },
        parameters: {
          seed: 42,
          result_format: "message"
        }
      };
    } else {
      let textToAnalyze = typeof content === 'string' ? content : "";
      if (content instanceof Blob && !isMultimodal) {
        textToAnalyze = await extractTextFromDocx(content);
      }

      payload = {
        model: "qwen-max",
        input: {
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: `Analyze this essay: ${textToAnalyze}` }
          ]
        },
        parameters: {
          seed: 42,
          temperature: 0,
          result_format: "message"
        }
      };
    }

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.API_KEY}`
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) throw new Error(`Qwen API Error: ${response.statusText}`);

    const data = await response.json();
    const contentText = isMultimodal 
      ? data.output.choices[0].message.content[0].text 
      : data.output.choices[0].message.content;

    // Extract JSON from the markdown response if necessary
    const jsonMatch = contentText.match(/\{[\s\S]*\}/);
    const result = JSON.parse(jsonMatch ? jsonMatch[0] : contentText);

    return {
      score: result.score || 0,
      reason: result.reason || "Processed with Qwen-Max.",
      summary: result.summary || "Summary generated by Qwen.",
      isSuspectedAI: result.isSuspectedAI || false,
      status: 'completed'
    };
  } catch (error) {
    console.error("Qwen Scoring Error:", error);
    return {
      score: 0,
      reason: "Error communicating with Qwen API.",
      summary: "Could not process document via DashScope.",
      isSuspectedAI: false,
      status: 'error'
    };
  }
};
